version: '3'

services:

  redis:
    image: redis:alpine
    ports:
    - "6379"
    networks:
    - frontend
    - backend
  #    deploy:
  #      replicas: 2
  #      update_config:
  #        parallelism: 2
  #        delay: 10s
  #      restart_policy:
  #        condition: on-failure
  rabbitmq:
    image: bitnami/rabbitmq:latest

  registry:
    image: breath-cloud-demo-registry:1.0-SNAPSHOT
    environment:
    - spring.profiles.active=docker
    ports:
    - "8761"
    networks:
    - frontend
    - backend
    
  config:
    image: breath-cloud-demo-config:1.0-SNAPSHOT
    environment:
    - spring.profiles.active=docker,composite
    ports:
    - "8888"
    networks:
    - frontend
    - backend

networks:
  frontend:
  backend: